MODEL_NAME = "rescnn"  # cnn, rescnn, conformer, ecapa
EMB_DIM = 192
DROPOUT = 0.3

CONFORMER_D_MODEL = 144
CONFORMER_DROPOUT = 0.1
CONFORMER_NUM_HEADS = 4
CONFORMER_FF_MULT = 4
CONFORMER_CONV_KERNEL_SIZE = 31
CONFORMER_NUM_BLOCKS = 4

ECAPA_CHANNELS = 512
ECAPA_MFA_CHANNELS = 1536
ECAPA_ATTENTION_CHANNELS = 256
ECAPA_SCALE = 8
ECAPA_SE_BOTTLENECK = 128
ECAPA_DROPOUT = 0.0
