BATCH_SIZE = 64
EPOCHS = 30
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-4

LR_SCHEDULER = "none"
LR_FACTOR = 0.5
LR_PATIENCE = 2
MIN_LR = 1e-6
COSINE_T_MAX = EPOCHS
COSINE_ETA_MIN = MIN_LR

TRIPLET_MARGIN = 0.22
P = 12
K = 5

TRAIN_FEATURE_MODE = "clean+noise"
