EPOCHS = 30
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-4

LR_FACTOR = 0.5
LR_PATIENCE = 2
MIN_LR = 1e-6
COSINE_T_MAX = EPOCHS
COSINE_ETA_MIN = MIN_LR

MARGIN = 0.22
P = 12
K = 5

LIGHTWEIGHT_VERIFY_EVERY_N_EPOCHS = 0
LIGHTWEIGHT_VERIFY_SPLIT = "dev_clean"
LIGHTWEIGHT_VERIFY_SAME_PAIRS = 2000
LIGHTWEIGHT_VERIFY_DIFF_PAIRS = 2000
